### ISSUE TITLE
Not working with angular-bootstrap 0.14.+

### ISSUE THREAD

**Issue by ArielCabib** [Elijen/angular-popover-toggle#3]
Might be all the uib- prefixes they added?

**Comment by ManasviA** [comment]
Fixed in pull request "angular bootstrap v0.14.3 fix". It was because in 0.14.3, angular-bootstrap has started using native JS events instead of jquery based events.

**Comment by Elijen** [comment]
Yes, should be fixed in `v0.1.1`, thanks @ManasviA.

**Comment by canvas-manik** [comment]
Is this issue fixed in v0.1.1? Is still see $tooltipProvider in popover-toggle.js

https://github.com/Elijen/angular-popover-toggle/blob/v0.1.1/popover-toggle.js#L9
https://github.com/Elijen/angular-popover-toggle/blob/master/popover-toggle.js#L9

**Comment by Elijen** [comment]
@canvas-manik I didn't have time to investigate yet, but I think angular-popover-toggle should not be needed after angular-bootstrap v0.14.3 as `is-open` attribute was added.
