### ISSUE TITLE
package.json not present within the zip nor the tar.gz file

### ISSUE THREAD

**Issue by maximus221** [Elijen/angular-popover-toggle#4]
Hi, 

I'm trying to use this module but I'm not able to do so because I'm using npm (through webpack) instead of bower.

In order to fix this problem, all I need is to have the package.json file added to the release zip and/or tar.gz files. All this is for version 0.0.10.

By the way, great job!!!

Thanks in Advance

**Comment by Elijen** [comment]
Hi, I am not really sure how to fix this. `package.json` is in the repo.
